### ISSUE TITLE
HepMC correct configuration

### ISSUE THREAD

**Issue by fcpenha** [alisw/crmc#1]
I'd like to know what is the correct units to choose in the installation of HepMC, which is a pre-requisite to CRMC. Or, does it even matter? For example, below I choose GeV and cm:

```
./configure --prefix=/usr --with-momentum=GEV --with-length=CM
```

**Comment by ktf** [comment]
Someone in @alisw/pwgmm should probably answer this, but I suspect @qgp is away.

My naive answer is that since the official copy of HepMC uses:

```
cmake  $SOURCEDIR                           \
       -Dmomentum=GEV                       \
       -Dlength=MM                          \
       -Dbuild_docs:BOOL=OFF                \
       -DCMAKE_INSTALL_PREFIX=$INSTALLROOT
```

(i.e. GeV and mm) you probably want to stick with the same setup. That said, you can use alibuild to build exactly as things are deployed on the grid by following the tutorial at:

https://alisw.github.io/alibuild/tutorial.html

Just substitute `AliPhysics` with `crmc` and you should be fine.

**Comment by fcpenha** [comment]
I am worried because of choices that must be made afterwards, such as

```
!for other particles, please ask authors ... or use minimum ctau (cm) :
MinDecayLength  1.    !minimum c.Tau to define stable particles (cm)
```

as written in crmc.param.in

**Comment by fcpenha** [comment]
When I look carefully into the files generated after doing

```
aliBuild init crmc
```

I find a file alidist/hepmc.sh, containing:

```
cmake  $SOURCEDIR                           \
       -Dmomentum=GEV                       \
       -Dlength=MM                          \
       -Dbuild_docs:BOOL=OFF                \
       -DCMAKE_INSTALL_PREFIX=$INSTALLROOT
```

So, I agree with you @ktf .

**Comment by ktf** [comment]
Great. Can you close this?
